#
# Reference:
# https://zgadzaj.com/development/docker/docker-compose/containers/rabbitmq
#
version: "3.7"
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    build: .
    container_name: rabbitmq-topic
    ports:
      # AMQP
      - 5672:5672
      # rabbitMQ management
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
